GET http://127.0.0.1/pdf_files/1.pdf:8080
GET http://127.0.0.1/images/aa.jpg:8080
GET http://127.0.0.1/serv/index.html:8080
GET http://127.0.0.1/other_files/ab.cpp:8080
PUT http://127.0.0.1/images:8080 ab.jpg
PUT http://127.0.0.1/other_files:8080 p.c
PUT http://127.0.0.1/pdf_files:8080 folder/ic.pdf
